name: Sync Project Files to Hugging Face

on:
  push:
    paths:
      - 'data/**'
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'TODO.md'

jobs:
  upload-to-hugging-face:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub
      - name: Login to Hugging Face
        run: huggingface-cli login ${{ secrets.HUGGINGFACE_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.email "biligcrawl@gmail.com"
          git config --global user.name "Bilig Crawl"
      - name: Upload Project Files to Hugging Face
        run: |
          cd data
          git init
          git add .
          git commit -m "Update project files"
          git remote remove origin || true
          git remote add origin https://huggingface.co/datasets/biligcrawl/WikipediaTR
          git pull origin master --allow-unrelated-histories -X theirs
          git push -u origin master
        env:
          HF_HOME: '${{ github.workspace }}/.huggingface'
